name: polymerdart_ignore_binding_type
environment:
  sdk: '>=1.11.0'
dependencies:
  polymer: '^0.16.0'
dev_dependencies:
  ghpages_generator: '>=0.3.0 <0.4.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
